### ISSUE TITLE
Add production deployment and improve CI/CD

### ISSUE THREAD

**Issue by tomjohn1028** [mithraiclabs/psyoptions-frontend#420]
Update the Market Tracker CodePipeline flow to include a manual trigger to move from staging to production.

- [x] Create a pipeline flow that creates a temporary staging environment
- [x] Add a manual trigger that when triggered will and spin up the production
- [x] tear down the staging environment after production deployment
- [ ] ?? Send a notification when waiting for a manual trigger
