### ISSUE TITLE
Launch tasks

### ISSUE THREAD

**Issue by tomjohn1028** [mithraiclabs/psyoptions-frontend#473]
Blockers 
- [x] Change default assets contract size based on what is available (related to https://github.com/mithraiclabs/psyoptions-frontend/issues/433)
- [x] Instead of reading PsyOptons and DEX program ID from environment variables it should be read from the market-meta package (https://github.com/mithraiclabs/psyoptions-frontend/issues/474)
- [x] GEO-fencing (https://github.com/mithraiclabs/psyoptions-frontend/issues/416)
- [x] Add jurisdiction notice (https://github.com/mithraiclabs/psyoptions-frontend/issues/477)
- [x] Secure Hasura endpoints (https://github.com/mithraiclabs/psyoptions-market-tracker/issues/11)
- [x] Add disclaimer https://github.com/mithraiclabs/psyoptions-frontend/issues/483
- [x] Update RPC urls to use custom cluster
- [x] Push to mainnet
- [x] Spin up BTC and ETH markets as discussed with MM partner
- [x] Add market meta data to the market-meta package
- [x] Launch mainnet market tracker
- [x] Make sure Alameda is cranking markets
- [x] Release UI with mainnet showing

Non-blockers but other thoughts
* ~~Come up with process for adding new markets and getting those new markets into the market-meta package~~
    * ~~This could be just logged on the Initialize Market page~~
